enum EstimationUnit {
  HOURS_PER_DAY = "HOURS_PER_DAY",
  HOURS_PER_WEEK = "HOURS_ PER_WEEK",
  HOURS_PER_MONTH = "HOURS_PER_MONTH",
  DAYS_PER_MONTH = "DAYS_PER_MONTH",
  DAYS_PER_YEAR = "DAYS_PER_YEAR",
  FULL_TIME = "FULL_TIME",
  PART_TIME = "PART_TIME",
  FLEXIBLE = "FLEXIBLE",
}

enum ExperienceLevel {
  ENTRY_LEVEL = "ENTRY_LEVEL",
  INTERMEDIATE = "INTERMEDIATE",
  EXPERT = "EXPERT",
}

export { EstimationUnit, ExperienceLevel };
